package:
  name: toolchain3-rpi3
  version: 0.5

build:
  number: 0

test:
  commands:
    # Verify the scripts are in-place.
    {% for state in ["activate", "deactivate"] %}
    - test -f "${PREFIX}/etc/conda/{{ state }}.d/${PKG_NAME}_{{ state }}.sh"                # [unix]
    {% endfor %}

about:
  home: https://github.com/gaiar/toolchain3-feedstock
  license: BSD 3-Clause
  summary: A meta-package to enable the right toolchain.

extra:
  recipe-maintainers:
    - gaiar
